name = "pb"
compatibility_date = "2023-01-28"

account_id = "50c4da3a4bbe4486bf02c9a46b6bf37e"
# workers_dev = false
main = "src/index.js"

# config for default production environment
# yarn wrangler kv:namespace create PB
vars = { ENVIRONMENT = "production" }
# route = { pattern = "pb.ebridge.workers.dev", custom_domain = true }
kv_namespaces = [
  { binding = "PB", id = "caf2498da3f74456be357297bcfebe1f" },
]


